name: Webhook

on:
  push:
    branches:
      'main'
    paths:
      - 'syncstorage-rs.spec'
  workflow_call:
  workflow_dispatch:

jobs:
  copr:
    name: Trigger build on COPR
    runs-on: ubuntu-slim
    steps:
      - uses: felfert/copr-build-action@v1
        with:
          url: ${{ secrets.COPR_WEBHOOK }}
          force: true
